-- MCAN Southwest Backend — initial schema
-- Reflects MCAN_Southwest_Backend_API_Docs.md v1.0 (Mongo fields mapped to MySQL columns)

CREATE TABLE users (
  id                        INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  first_name                VARCHAR(100) NOT NULL,
  last_name                 VARCHAR(100) NOT NULL,
  email                     VARCHAR(255) NOT NULL UNIQUE,
  password_hash             VARCHAR(255) NULL,
  phone                     VARCHAR(30),
  role                      ENUM('member','admin','superadmin') NOT NULL DEFAULT 'member',
  member_id                 VARCHAR(30) UNIQUE,
  membership_type           ENUM('full','associate','student','corporate'),
  status                    ENUM('active','pending','suspended','deactivated') NOT NULL DEFAULT 'pending',
  state                     VARCHAR(100),
  chapter                   VARCHAR(150),
  occupation                VARCHAR(150),
  profile_photo             VARCHAR(500),
  digital_id_status         ENUM('none','pending','approved','rejected','revoked') NOT NULL DEFAULT 'none',
  is_email_verified         TINYINT(1) NOT NULL DEFAULT 0,
  email_verification_token VARCHAR(255),
  password_reset_token_hash VARCHAR(255),
  password_reset_expiry     DATETIME NULL,
  invite_token_hash         VARCHAR(255),
  invite_expires_at         DATETIME NULL,
  last_login                DATETIME NULL,
  is_deleted                TINYINT(1) NOT NULL DEFAULT 0,
  created_at                DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at                DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_users_role (role),
  INDEX idx_users_status (status),
  INDEX idx_users_state (state)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE refresh_tokens (
  id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id     INT UNSIGNED NOT NULL,
  token_hash  VARCHAR(255) NOT NULL,
  expires_at  DATETIME NOT NULL,
  revoked_at  DATETIME NULL,
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_rt_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE news (
  id           INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title        VARCHAR(255) NOT NULL,
  slug         VARCHAR(280) NOT NULL UNIQUE,
  content      MEDIUMTEXT,
  excerpt      VARCHAR(300),
  category     ENUM('announcement','news','press-release','update') NOT NULL,
  cover_image  VARCHAR(500),
  author_id    INT UNSIGNED NOT NULL,
  tags         JSON,
  featured     TINYINT(1) NOT NULL DEFAULT 0,
  status       ENUM('draft','published','archived') NOT NULL DEFAULT 'draft',
  published_at DATETIME NULL,
  read_time    SMALLINT UNSIGNED,
  is_deleted   TINYINT(1) NOT NULL DEFAULT 0,
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (author_id) REFERENCES users(id),
  INDEX idx_news_status_published (status, published_at),
  INDEX idx_news_category (category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE events (
  id                  INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title               VARCHAR(255) NOT NULL,
  slug                VARCHAR(280) NOT NULL UNIQUE,
  description         MEDIUMTEXT,
  category            ENUM('meeting','conference','seminar','workshop','social','other') NOT NULL,
  cover_image         VARCHAR(500),
  location_venue      VARCHAR(255),
  location_address    VARCHAR(500),
  location_city       VARCHAR(100),
  location_state      VARCHAR(100),
  is_online           TINYINT(1) NOT NULL DEFAULT 0,
  online_link         VARCHAR(500),
  start_date          DATETIME NOT NULL,
  end_date            DATETIME,
  capacity            INT UNSIGNED,
  registered_count    INT UNSIGNED NOT NULL DEFAULT 0,
  is_free             TINYINT(1) NOT NULL DEFAULT 1,
  price               DECIMAL(10,2) NOT NULL DEFAULT 0,
  organizer_contact   VARCHAR(255),
  status              ENUM('draft','published','cancelled') NOT NULL DEFAULT 'draft',
  cancellation_reason VARCHAR(500),
  author_id           INT UNSIGNED NOT NULL,
  is_deleted          TINYINT(1) NOT NULL DEFAULT 0,
  created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (author_id) REFERENCES users(id),
  INDEX idx_events_start (start_date),
  INDEX idx_events_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE contacts (
  id         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ticket_id  VARCHAR(30) NOT NULL UNIQUE,
  first_name VARCHAR(100) NOT NULL,
  last_name  VARCHAR(100) NOT NULL,
  email      VARCHAR(255) NOT NULL,
  phone      VARCHAR(30),
  subject    VARCHAR(255) NOT NULL,
  category   ENUM('general','membership','events','partnership','complaint','other') NOT NULL,
  message    TEXT NOT NULL,
  is_read    TINYINT(1) NOT NULL DEFAULT 0,
  read_at    DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_contacts_read (is_read)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE digital_ids (
  id                 INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  member_id          INT UNSIGNED NOT NULL,
  passport_photo     VARCHAR(500) NOT NULL,
  signature          VARCHAR(500),
  status             ENUM('pending','approved','rejected','revoked') NOT NULL DEFAULT 'pending',
  card_image_url     VARCHAR(500),
  card_pdf_url       VARCHAR(500),
  card_image_public_id VARCHAR(255),
  card_pdf_public_id VARCHAR(255),
  issued_at          DATETIME NULL,
  expiry_date        DATETIME NULL,
  approved_by        INT UNSIGNED NULL,
  rejected_by        INT UNSIGNED NULL,
  revoked_by         INT UNSIGNED NULL,
  approval_note      VARCHAR(500),
  rejection_reason   VARCHAR(500),
  revocation_reason  VARCHAR(500),
  additional_note    VARCHAR(500),
  submitted_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted         TINYINT(1) NOT NULL DEFAULT 0,
  created_at         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (member_id) REFERENCES users(id),
  FOREIGN KEY (approved_by) REFERENCES users(id),
  FOREIGN KEY (rejected_by) REFERENCES users(id),
  FOREIGN KEY (revoked_by) REFERENCES users(id),
  INDEX idx_did_status (status),
  INDEX idx_did_member (member_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
